title: "NGFⓧAGORA in Asia: 2024 Spring Workshop"
description: NGFxAGORA Spring Workshop Homepage

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: Program
      url: /program
    - title: Participants
      url: /participants
    - title: Venue & Travel
      url: /venue
    - title: Contact Us
      url: /contact

social:
    email: wispedia@snu.ac.kr

google_analytics: "UA-58263416-1"

disqus:
    shortname: agora
